### ISSUE TITLE
[QET]: Test Documentation: Master Test Plan, Test Strategy, Test Plan

### ISSUE THREAD

**Issue by szikszail** [Idea-Pool/topics#105]
### 1.1. Title

Test Documentation: Master Test Plan, Test Strategy, Test Plan

### 1.2. Details

This workshop would be a place to discuss our understanding of Test documentation in general and various types of test documentation practices, including Master test plan, Test strategy, and Test Plan.

The goal is to create a comprehensive, overall picture of the different test documentation approaches, taking into account the broad and colorful understanding of them from different business domains, SDLCs, experience levels, and "testing schools".

### 2.1. Area

Management, Testing

### 3.1. Stream

Competency Development (assisting engineer to grow professionally)

### 4.1. Format

Workshop (working together offline during an offline workshop)

### 5.1. Artifact

Article (an article on the Idea Pool WeAreCommunity page), Meetup (an event on the Idea Pool WeAreCommunity page)

## Tasks: Quality Engineering Talks

- [ ] @Idea-Pool/idea-pool-staff-team: Create the event (WAC): TBD
- [ ] @Idea-Pool/idea-pool-staff-team: Advertise the event and invite participants
- [ ] @Idea-Pool/idea-pool-staff-team: Prepare for the workshop
- [ ] @Idea-Pool/idea-pool-staff-team: Conduct the workshop
- [ ] @Idea-Pool/idea-pool-staff-team: Upload notes, research, and summary to MS Teams
