### ISSUE TITLE
[QET]: Test types / Test levels

### ISSUE THREAD

**Issue by szikszail** [Idea-Pool/topics#20]
### 1.1. Title

Test types / Test levels

### 1.2. Details

This workshop would be a place to discuss our understanding of Test types and levels, what these are, how to understand them in various contexts and platforms, etc.

The goal is to create a comprehensive, overall picture of the different test types and levels, taking into account the broad and colorful understanding of them from different business domains, technologies, experience levels, and "testing schools".

Part of: https://github.com/Idea-Pool/topics/issues/41

### 2.1. Area

Testing

### 3.1. Stream

Competency Development (assisting engineer to grow professionally)

### 4.1. Format

Workshop (working together offline during an offline workshop)

### 5.1. Artifact

Article (an article on the Idea Pool WeAreCommunity page), Meetup (an event on the Idea Pool WeAreCommunity page)

## Tasks

- [x] @Idea-Pool/idea-pool-staff-team: Create the event (WAC): https://wearecommunity.io/events/qet-test-levels-test-types
- [x] @Idea-Pool/idea-pool-staff-team: Advertise the event and invite participants
- [x] @Idea-Pool/idea-pool-staff-team: Prepare for the workshop
- [x] @Idea-Pool/idea-pool-staff-team: Conduct the workshop
- [x] @Idea-Pool/idea-pool-staff-team: Upload notes, research, and summary to MS Teams
