### ISSUE TITLE
[TA Tool Evaluation]: Cypress vs. Playwright

### ISSUE THREAD

**Issue by szikszail** [Idea-Pool/topics#22]
### 1.1. Title

Cypress vs. Playwright

### 1.2. Details

Tool comparison from a different view.

### 2.1. Area

Test Automation

### 3.1. Stream

Test Automation Tool Evaluation (aiding engineers with the test automation tool evaluation practices)

### 4.1. Format

Demo (demonstrating the idea in an online event)

### 5.1. Artifact

Software (a source code and/or a delivered software/package), Talk (a talk on the Idea Pool WeAreCommunity page)

## Tasks

- [ ] @Idea-Pool/idea-pool-staff-team: Create evaluation repository: TBD
- [ ] @Idea-Pool/idea-pool-staff-team: Create the event (WAC): TBD
- [ ] TBD: Use the repository to implement at least the given test cases with the tool
- [ ] TBD: Create a presentation to introduce the tool, summarize its features and use cases
- [ ] TBD: Include the results and findings of the implementation in the presentation
- [ ] TBD: Demonstrate the presentation
- [ ] @Idea-Pool/idea-pool-staff-team: Upload the recording (VideoPortal): TBD
- [ ] @Idea-Pool/idea-pool-staff-team: Upload the slides (PDF): TBD
