### ISSUE TITLE
[TA Tool Evaluation]: Frisby JS

### ISSUE THREAD

**Issue by szikszail** [Idea-Pool/topics#30]
### 1.1. Title

Frisby JS

### 1.2. Details

This task aims to introduce and evaluate the Frisby JS test automation framework by briefly introducing its features and a practical evaluation of its usability for typical test automation tasks.

#### Framework
- Name: Frisby JS
- URL: https://docs.frisbyjs.com/

### 2.1. Area

Test Automation

### 3.1. Stream

Test Automation Tool Evaluation (aiding engineers with the test automation tool evaluation practices)

### 4.1. Format

Demo (demonstrating the idea in an online event)

### 5.1. Artifact

Software (a source code and/or a delivered software/package), Talk (a talk on the Idea Pool WeAreCommunity page)

## Tasks

- [x] @Idea-Pool/idea-pool-staff-team: Create evaluation repository: https://github.com/Idea-Pool/evaluation-js-frisby
- [x] @Idea-Pool/idea-pool-staff-team: Create the event (WAC): https://wearecommunity.io/events/idea-pool-ta-tool-evaluation-frisby-js
- [x] @MonikaLaszlo: Use the repository to implement at least the given test cases with the tool
- [x] @MonikaLaszlo: Create a presentation to introduce the tool, summarize its features and use cases
- [x] @MonikaLaszlo: Include the results and findings of the implementation in the presentation
- [x] @MonikaLaszlo: Demonstrate the presentation
- [x] @Idea-Pool/idea-pool-staff-team: Upload the recording (VideoPortal): https://videoportal.epam.com/video/dYoD5NJ3
- [x] @Idea-Pool/idea-pool-staff-team: Upload the slides (PDF): [idea-pool-ta-tool-evaluation-frisby.pdf](https://github.com/Idea-Pool/topics/files/11732645/idea-pool-ta-tool-evaluation-frisby.pdf)

**Comment by MonikaLaszlo** [comment]
[idea-pool-ta-tool-evaluation-frisby.pptx](https://github.com/Idea-Pool/topics/files/11725797/idea-pool-ta-tool-evaluation-frisby.pptx)

**Comment by MonikaLaszlo** [comment]
[idea-pool-ta-tool-evaluation-frisby.pdf](https://github.com/Idea-Pool/topics/files/11732645/idea-pool-ta-tool-evaluation-frisby.pdf)
