### ISSUE TITLE
[TA Tool Evaluation]: Robot Framework

### ISSUE THREAD

**Issue by szikszail** [Idea-Pool/topics#31]
### 1.1. Title

Robot Framework

### 1.2. Details

This task aims to introduce and evaluate the Robot Framework test automation framework by briefly introducing its features and a practical evaluation of its usability for typical test automation tasks.

#### Framework

- Name: Robot Framework
- URL: https://robotframework.org/

#### Tasks

1. Create a presentation introducing the tool and summarizing its features and use cases.
2. Use the https://github.com/Idea-Pool/evaluation-py-robot repository to implement at least the given test cases with the tool
3. Include the results and findings of the implementation in the presentation
4. Demonstrate the presentation

### 2.1. Area

Test Automation

### 3.1. Stream

Test Automation Tool Evaluation (aiding engineers with the test automation tool evaluation practices)

### 4.1. Format

Demo (demonstrating the idea in an online event)

### 5.1. Artifact

Software (a source code and/or a delivered software/package), Talk (a talk on the Idea Pool WeAreCommunity page)

### Process

- [x] Presentation: [idea-pool-ta-tool-evaluation-robot-framework-laszlo-szikszai.pptx](https://github.com/Idea-Pool/topics/files/11147774/idea-pool-ta-tool-evaluation-robot-framework-laszlo-szikszai.pptx)
- [x] Presentation review
- [x] Event: https://wearecommunity.io/events/idea-pool-ta-tool-evaluation-robot-framework
- [x] Recording: https://videoportal.epam.com/video/qJXjNeaw
- [x] Q&A: https://wearecommunity.io/events/idea-pool-ta-tool-evaluation-robot-framework/qa-session/3328
- [x] Slides
- [x] Links/Repository

**Comment by szikszail** [comment]
Presented on 2023.04.24 by @szikszail. Moderated by @sorosz89.
