### ISSUE TITLE
[QET]: Calculate ROI

### ISSUE THREAD

**Issue by szikszail** [Idea-Pool/topics#37]
### 1.1. Title

Calculate ROI

### 1.2. Details

These workshops will aim to check various examples for calculating ROI. For example,
1. Test automation on a project starting, using SCRUM, with different team setups and application type
2. Test automation for certain test cases or features

Part of: https://github.com/Idea-Pool/topics/issues/41

### 2.1. Area

Management, Test Automation, Testing

### 3.1. Stream

Competency Development (assisting engineer to grow professionally)

### 4.1. Format

Workshop (working together offline during an offline workshop)

### 5.1. Artifact

Article (an article on the Idea Pool WeAreCommunity page), Meetup (an event on the Idea Pool WeAreCommunity page)

## Tasks: Quality Engineering Talks

- [x] @Idea-Pool/idea-pool-staff-team: Create the event (WAC): https://wearecommunity.io/events/qet-roi
- [x] @Idea-Pool/idea-pool-staff-team: Advertise the event and invite participants
- [x] @Idea-Pool/idea-pool-staff-team: Prepare for the workshop
- [x] @Idea-Pool/idea-pool-staff-team: Conduct the workshop
- [x] @Idea-Pool/idea-pool-staff-team: Upload notes, research, and summary to MS Teams

## Use-case

**Test Automation ROI Calculation for "TechSolutions"**

* **Company Name:** TechSolutions
* **Application:** "TechPay" - Digital Payment Platform

**Objective:** The objective is to calculate the Return on Investment (ROI) for introducing test automation in the "TechPay" project at TechSolutions.

**Project Overview:** TechSolutions has been developing "TechPay," a digital payment platform using SCRUM with 2-week sprints. The project currently has 500 manual test cases, categorized as smoke and regression suites (20% - 80%). All test cases are automatable. The regression suite is executed twice per sprint.

**Desired Outcome:** TechSolutions aims to automate all 500 test cases and set up a CI/CD pipeline to improve testing efficiency by setting up a team with 2 test automation engineers.
