### ISSUE TITLE
[Idea]: Testing Library - Testing React Applications

### ISSUE THREAD

**Issue by szikszail** [Idea-Pool/topics#44]
### 1.1. Title

Testing Library - Testing React Applications

### 1.2. Details

This task aims to introduce and evaluate the *Testing Library* test automation framework by giving a detailed introduction of its features and practical guides for typical test automation tasks to test React applications.

#### Framework
* Name: Testing Library
* URL: https://testing-library.com/

#### Tasks
- [ ] Create a presentation to introduce the tool, to summarize its features and use cases
- [ ] Create a repository to implement certain test cases with the tool
- [ ] Include the results and findings of the implementation in the presentation
- [ ] Demonstrate the presentation

### 2.1. Area

Test Automation

### 3.1. Stream

Competency Development (assisting engineer to grow professionally)

### 4.1. Format

Demo (demonstrating the idea in an online event)

### 5.1. Artifact

Software (a source code and/or a delivered software/package), Talk (a talk on the Idea Pool WeAreCommunity page)

**Comment by szikszail** [comment]
Migrated from https://jira.epam.com/jira/browse/EPMDEBIP-344
