### ISSUE TITLE
[TA Tool Evaluation]: Allure TestOps

### ISSUE THREAD

**Issue by szikszail** [Idea-Pool/topics#54]
### 1.1. Title

Allure TestOps

### 1.2. Details

This task aims to introduce and evaluate the Allure TestOps tool by briefly introducing its features and a practical evaluation of its usability.

#### Framework

- Name: Allure TestOps
- URL: https://qameta.io/

### 2.1. Area

DevOps, Software Development, Test Automation, Testing

### 3.1. Stream

Test Automation Tool Evaluation (aiding engineers with the test automation tool evaluation practices)

### 4.1. Format

Demo (demonstrating the idea in an online event)

### 5.1. Artifact

Software (a source code and/or a delivered software/package), Talk (a talk on the Idea Pool WeAreCommunity page)

## Tasks

- [ ] @Idea-Pool/idea-pool-staff-team: Create evaluation repository: TBD
- [ ] @Idea-Pool/idea-pool-staff-team: Create the event (WAC): TBD
- [ ] TBD: Use the repository to implement at least the given test cases with the tool
- [ ] TBD: Create a presentation to introduce the tool, summarize its features and use cases
- [ ] TBD: Include the results and findings of the implementation in the presentation
- [ ] TBD: Demonstrate the presentation
- [ ] @Idea-Pool/idea-pool-staff-team: Upload the recording (VideoPortal): TBD
- [ ] @Idea-Pool/idea-pool-staff-team: Upload the slides (PDF): TBD

**Comment by szikszail** [comment]
Migrated from https://jira.epam.com/jira/browse/EPMDEBIP-333
