### ISSUE TITLE
[TA Tool Evaluation]: Taurus

### ISSUE THREAD

**Issue by szikszail** [Idea-Pool/topics#58]
### 1.1. Title

Taurus

### 1.2. Details

This task aims to introduce and evaluate the **Taurus** test automation framework by briefly introducing its features and a practical evaluation of its usability for typical test automation tasks.

#### Framework

- Name: Taurus
- URL: https://gettaurus.org/

### 2.1. Area

Test Automation

### 3.1. Stream

Test Automation Tool Evaluation (aiding engineers with the test automation tool evaluation practices)

### 4.1. Format

Demo (demonstrating the idea in an online event)

### 5.1. Artifact

Software (a source code and/or a delivered software/package), Talk (a talk on the Idea Pool WeAreCommunity page)

## Tasks

- [ ] @Idea-Pool/idea-pool-staff-team: Create evaluation repository: TBD
- [ ] @Idea-Pool/idea-pool-staff-team: Create the event (WAC): TBD
- [ ] @gula123: Use the repository to implement at least the given test cases with the tool
- [ ] @gula123: Create a presentation to introduce the tool, summarize its features and use cases
- [ ] @gula123: Include the results and findings of the implementation in the presentation
- [ ] @gula123: Demonstrate the presentation
- [ ] @Idea-Pool/idea-pool-staff-team: Upload the recording (VideoPortal): TBD
- [ ] @Idea-Pool/idea-pool-staff-team: Upload the slides (PDF): TBD

**Comment by szikszail** [comment]
Migrated from https://jira.epam.com/jira/browse/EPMDEBIP-324
