### ISSUE TITLE
[TA Tool Evaluation]: JBehave

### ISSUE THREAD

**Issue by szikszail** [Idea-Pool/topics#60]
### 1.1. Title

JBehave

### 1.2. Details

This task aims to introduce and evaluate the **JBehave** test automation framework by briefly introducing its features and a practical evaluation of its usability for typical test automation tasks.

#### Framework

- Name: JBehave
- URL: https://jbehave.org/

#### Tasks

- [ ] Create a presentation to introduce the tool, to summarize its features and use cases
- [ ] Use the TBD repository to implement at least the given test cases with the tool
- [ ] Include the results and findings of the implementation in the presentation
- [ ] Demonstrate the presentation

### 2.1. Area

Test Automation

### 3.1. Stream

Test Automation Tool Evaluation (aiding engineers with the test automation tool evaluation practices)

### 4.1. Format

Demo (demonstrating the idea in an online event)

### 5.1. Artifact

Software (a source code and/or a delivered software/package), Talk (a talk on the Idea Pool WeAreCommunity page)

**Comment by szikszail** [comment]
Migrated from https://jira.epam.com/jira/browse/EPMDEBIP-321
