### ISSUE TITLE
[TA Tool Evaluation]: Pytest + Selenium + Allure

### ISSUE THREAD

**Issue by szikszail** [Idea-Pool/topics#65]
### 1.1. Title

Pytest + Selenium + Allure

### 1.2. Details

This task aims to introduce and evaluate the **Pytest**, **Selenium**, and **Allure** test automation frameworks by briefly introducing their features and a practical evaluation of their usability for typical test automation tasks.

#### Frameworks

- Pytest: https://docs.pytest.org/en/7.3.x/
- Selenium: https://pytest-selenium.readthedocs.io/en/latest/user_guide.html
- Allure: https://pypi.org/project/allure-pytest/

#### Tasks

- [ ] Create a presentation to introduce the tool, summarize its features and use cases
- [ ] Use the <TI>TBD</TI> repository to implement at least the given test cases with the tool
- [ ] Include the results and findings of the implementation in the presentation
- [ ] Demonstrate the presentation

### 2.1. Area

Test Automation

### 3.1. Stream

Test Automation Tool Evaluation (aiding engineers with the test automation tool evaluation practices)

### 4.1. Format

Demo (demonstrating the idea in an online event)

### 5.1. Artifact

Software (a source code and/or a delivered software/package), Talk (a talk on the Idea Pool WeAreCommunity page)

**Comment by szikszail** [comment]
Migrated from https://jira.epam.com/jira/browse/EPMDEBIP-319
